apiVersion: v1
kind: Service
metadata:
  name: metric-service
spec:
  selector:
    app: metric-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4200
  type: LoadBalancer
